modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="vikare"
version="${file.jarVersion}"
displayName="Vikare"
authors="appw"
credits="Cammie"
description='''
a not very original port of a mod
'''
[[dependencies.Vikare]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.Vikare]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.Vikare]]
   modId="curios"
   mandatory=true
   versionRange="[1.16.5-4.0.3.5,1.17.1-5.0.0.0)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.Vikare]]
   modId="caelus"
   mandatory=true
   versionRange="[1.16.5-2.1.3.1,)"
   ordering="AFTER"
   side="BOTH"