modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="vikare"
version="${file.jarVersion}"
displayName="Vikare"
authors="appw"
credits="Cammie"
description='''
a not very original port of a mod
'''
logoFile="vikare.png"
[[dependencies.Vikare]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.Vikare]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.20.5)"
   ordering="NONE"
   side="BOTH"
[[dependencies.Vikare]]
   modId="curios"
   mandatory=true
   versionRange="[5.8.1+1.20.1,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies.Vikare]]
   modId="caelus"
   mandatory=true
   versionRange="[3.2.0+1.20.1,)"
   ordering="AFTER"
   side="BOTH"